/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ProfileIndexImport } from './routes/profile/index'
import { Route as BooksIndexImport } from './routes/books/index'
import { Route as AuthIndexImport } from './routes/auth/index'
import { Route as AuthRegisterImport } from './routes/auth/register'
import { Route as BooksBookSlugIndexImport } from './routes/books/$bookSlug/index'
import { Route as BooksBookSlugChaptersIndexImport } from './routes/books/$bookSlug/chapters/index'
import { Route as BooksBookSlugChaptersChapterIndexImport } from './routes/books/$bookSlug/chapters/$chapter/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileIndexRoute = ProfileIndexImport.update({
  path: '/profile/',
  getParentRoute: () => rootRoute,
} as any)

const BooksIndexRoute = BooksIndexImport.update({
  path: '/books/',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  path: '/auth/',
  getParentRoute: () => rootRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  path: '/auth/register',
  getParentRoute: () => rootRoute,
} as any)

const BooksBookSlugIndexRoute = BooksBookSlugIndexImport.update({
  path: '/books/$bookSlug/',
  getParentRoute: () => rootRoute,
} as any)

const BooksBookSlugChaptersIndexRoute = BooksBookSlugChaptersIndexImport.update(
  {
    path: '/books/$bookSlug/chapters/',
    getParentRoute: () => rootRoute,
  } as any,
)

const BooksBookSlugChaptersChapterIndexRoute =
  BooksBookSlugChaptersChapterIndexImport.update({
    path: '/books/$bookSlug/chapters/$chapter/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof rootRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof rootRoute
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksIndexImport
      parentRoute: typeof rootRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexImport
      parentRoute: typeof rootRoute
    }
    '/books/$bookSlug/': {
      id: '/books/$bookSlug/'
      path: '/books/$bookSlug'
      fullPath: '/books/$bookSlug'
      preLoaderRoute: typeof BooksBookSlugIndexImport
      parentRoute: typeof rootRoute
    }
    '/books/$bookSlug/chapters/': {
      id: '/books/$bookSlug/chapters/'
      path: '/books/$bookSlug/chapters'
      fullPath: '/books/$bookSlug/chapters'
      preLoaderRoute: typeof BooksBookSlugChaptersIndexImport
      parentRoute: typeof rootRoute
    }
    '/books/$bookSlug/chapters/$chapter/': {
      id: '/books/$bookSlug/chapters/$chapter/'
      path: '/books/$bookSlug/chapters/$chapter'
      fullPath: '/books/$bookSlug/chapters/$chapter'
      preLoaderRoute: typeof BooksBookSlugChaptersChapterIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth': typeof AuthIndexRoute
  '/books': typeof BooksIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/books/$bookSlug': typeof BooksBookSlugIndexRoute
  '/books/$bookSlug/chapters': typeof BooksBookSlugChaptersIndexRoute
  '/books/$bookSlug/chapters/$chapter': typeof BooksBookSlugChaptersChapterIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth': typeof AuthIndexRoute
  '/books': typeof BooksIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/books/$bookSlug': typeof BooksBookSlugIndexRoute
  '/books/$bookSlug/chapters': typeof BooksBookSlugChaptersIndexRoute
  '/books/$bookSlug/chapters/$chapter': typeof BooksBookSlugChaptersChapterIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/': typeof AuthIndexRoute
  '/books/': typeof BooksIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/books/$bookSlug/': typeof BooksBookSlugIndexRoute
  '/books/$bookSlug/chapters/': typeof BooksBookSlugChaptersIndexRoute
  '/books/$bookSlug/chapters/$chapter/': typeof BooksBookSlugChaptersChapterIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/register'
    | '/auth'
    | '/books'
    | '/profile'
    | '/books/$bookSlug'
    | '/books/$bookSlug/chapters'
    | '/books/$bookSlug/chapters/$chapter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/register'
    | '/auth'
    | '/books'
    | '/profile'
    | '/books/$bookSlug'
    | '/books/$bookSlug/chapters'
    | '/books/$bookSlug/chapters/$chapter'
  id:
    | '__root__'
    | '/'
    | '/auth/register'
    | '/auth/'
    | '/books/'
    | '/profile/'
    | '/books/$bookSlug/'
    | '/books/$bookSlug/chapters/'
    | '/books/$bookSlug/chapters/$chapter/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthIndexRoute: typeof AuthIndexRoute
  BooksIndexRoute: typeof BooksIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  BooksBookSlugIndexRoute: typeof BooksBookSlugIndexRoute
  BooksBookSlugChaptersIndexRoute: typeof BooksBookSlugChaptersIndexRoute
  BooksBookSlugChaptersChapterIndexRoute: typeof BooksBookSlugChaptersChapterIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthIndexRoute: AuthIndexRoute,
  BooksIndexRoute: BooksIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  BooksBookSlugIndexRoute: BooksBookSlugIndexRoute,
  BooksBookSlugChaptersIndexRoute: BooksBookSlugChaptersIndexRoute,
  BooksBookSlugChaptersChapterIndexRoute:
    BooksBookSlugChaptersChapterIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth/register",
        "/auth/",
        "/books/",
        "/profile/",
        "/books/$bookSlug/",
        "/books/$bookSlug/chapters/",
        "/books/$bookSlug/chapters/$chapter/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth/register": {
      "filePath": "auth/register.tsx"
    },
    "/auth/": {
      "filePath": "auth/index.tsx"
    },
    "/books/": {
      "filePath": "books/index.tsx"
    },
    "/profile/": {
      "filePath": "profile/index.tsx"
    },
    "/books/$bookSlug/": {
      "filePath": "books/$bookSlug/index.tsx"
    },
    "/books/$bookSlug/chapters/": {
      "filePath": "books/$bookSlug/chapters/index.tsx"
    },
    "/books/$bookSlug/chapters/$chapter/": {
      "filePath": "books/$bookSlug/chapters/$chapter/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
