/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ProfileIndexImport } from './routes/profile/index'
import { Route as BooksIndexImport } from './routes/books/index'
import { Route as AuthIndexImport } from './routes/auth/index'
import { Route as BooksBookSlugImport } from './routes/books/$bookSlug'
import { Route as AuthRegisterImport } from './routes/auth/register'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileIndexRoute = ProfileIndexImport.update({
  path: '/profile/',
  getParentRoute: () => rootRoute,
} as any)

const BooksIndexRoute = BooksIndexImport.update({
  path: '/books/',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  path: '/auth/',
  getParentRoute: () => rootRoute,
} as any)

const BooksBookSlugRoute = BooksBookSlugImport.update({
  path: '/books/$bookSlug',
  getParentRoute: () => rootRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  path: '/auth/register',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof rootRoute
    }
    '/books/$bookSlug': {
      id: '/books/$bookSlug'
      path: '/books/$bookSlug'
      fullPath: '/books/$bookSlug'
      preLoaderRoute: typeof BooksBookSlugImport
      parentRoute: typeof rootRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof rootRoute
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksIndexImport
      parentRoute: typeof rootRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/register': typeof AuthRegisterRoute
  '/books/$bookSlug': typeof BooksBookSlugRoute
  '/auth': typeof AuthIndexRoute
  '/books': typeof BooksIndexRoute
  '/profile': typeof ProfileIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/register': typeof AuthRegisterRoute
  '/books/$bookSlug': typeof BooksBookSlugRoute
  '/auth': typeof AuthIndexRoute
  '/books': typeof BooksIndexRoute
  '/profile': typeof ProfileIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth/register': typeof AuthRegisterRoute
  '/books/$bookSlug': typeof BooksBookSlugRoute
  '/auth/': typeof AuthIndexRoute
  '/books/': typeof BooksIndexRoute
  '/profile/': typeof ProfileIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/register'
    | '/books/$bookSlug'
    | '/auth'
    | '/books'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/register'
    | '/books/$bookSlug'
    | '/auth'
    | '/books'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/auth/register'
    | '/books/$bookSlug'
    | '/auth/'
    | '/books/'
    | '/profile/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  BooksBookSlugRoute: typeof BooksBookSlugRoute
  AuthIndexRoute: typeof AuthIndexRoute
  BooksIndexRoute: typeof BooksIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  BooksBookSlugRoute: BooksBookSlugRoute,
  AuthIndexRoute: AuthIndexRoute,
  BooksIndexRoute: BooksIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth/register",
        "/books/$bookSlug",
        "/auth/",
        "/books/",
        "/profile/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth/register": {
      "filePath": "auth/register.tsx"
    },
    "/books/$bookSlug": {
      "filePath": "books/$bookSlug.tsx"
    },
    "/auth/": {
      "filePath": "auth/index.tsx"
    },
    "/books/": {
      "filePath": "books/index.tsx"
    },
    "/profile/": {
      "filePath": "profile/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
