name: "interactive-comments-section-dev"

services:
  db:
    image: "postgres:15"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dev
    ports:
      - 5432:5432

volumes:
  postgres:
    driver: local
